#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/5145881P/work ensure=absent force=true
puppet resource file /tmp/5145881P/work ensure=directory
cd /tmp/5145881P/work
git clone https://github.com/22052679Asraf/POC_REPO.git
cp -p /tmp/5145881P/work/index.html /var/www/html

